
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

pen_term = 1
ult_term = 2
even_sum = 2
while ult_term <= 4000000
    new_term = pen_term + ult_term
    if mod(new_term,2)==0
        global even_sum = even_sum + new_term
    end
    global pen_term = ult_term
    global ult_term = new_term
end

println("The sum of the even-valued terms is " , even_sum)


# The sum of the even-valued terms is 4613732
